# Generated by Django 5.2 on 2026-04-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="sitter_profile",
        ),
        migrations.CreateModel(
            name="DeletedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.BigIntegerField(verbose_name="Прошлый id пользователя"),
                ),
                ("uuid", models.UUIDField(verbose_name="Прошлый UUID пользователя")),
                ("username", models.CharField(max_length=150, verbose_name="Почта")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Фамилия"
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отчество"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=1500, verbose_name="Информация"
                    ),
                ),
                (
                    "bookings_as_sitter",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Бронирования как ситтер"
                    ),
                ),
                (
                    "bookings_as_owner",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Бронирования как владелец"
                    ),
                ),
                (
                    "pets",
                    models.JSONField(blank=True, null=True, verbose_name="Питомцы"),
                ),
                (
                    "is_sitter",
                    models.BooleanField(
                        default=False, verbose_name="Был ли пользователь ситтером"
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Удаленный пользователь",
                "verbose_name_plural": "Удаленные пользователи",
                "indexes": [
                    models.Index(fields=["uuid"], name="deleted_user_uuid_idx"),
                    models.Index(fields=["username"], name="deleted_username_uuid_idx"),
                    models.Index(
                        condition=models.Q(("phone__isnull", False)),
                        fields=["phone"],
                        name="deleted_user_phone_idx",
                    ),
                ],
            },
        ),
    ]
