# Generated by Django 5.2 on 2026-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_city_alter_user_options_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, max_length=1500, verbose_name="Информация"
            ),
        ),
    ]
