# Generated by Django 5.2 on 2026-04-24 17:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_userphoto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userphoto",
            options={
                "verbose_name": "Фото пользователя",
                "verbose_name_plural": "Фото пользователей",
            },
        ),
    ]
