# Generated by Django 5.2 on 2026-04-24 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_userphoto_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
