# Generated by Django 5.2 on 2026-04-06 19:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_remove_booking_dog"),
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("dog", "Собака"),
                            ("cat", "Кошка"),
                            ("parrot", "Попугай"),
                            ("hamster", "Хомяк"),
                            ("other", "Другое"),
                        ],
                        default="dog",
                        max_length=20,
                        verbose_name="Тип животного",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя питомца")),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Возраст",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Питомец",
                "verbose_name_plural": "Питомцы",
            },
        ),
        migrations.DeleteModel(
            name="Dog",
        ),
    ]
