# Generated by Django 5.2 on 2026-04-12 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_pet_delete_dog"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="breed_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название породы"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="height",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Рост, см",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="weight",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(300),
                ],
                verbose_name="Вес, кг",
            ),
        ),
    ]
