# Generated by Django 5.2 on 2026-04-24 16:11

import django.core.validators
import django.db.models.deletion
import pets.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0005_alter_pet_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=pets.storages.pet_photo_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "bmp",
                                    "svg",
                                    "tiff",
                                    "ico",
                                ]
                            )
                        ],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "order_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Порядок отображения",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Основное фото"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="pets.pet",
                        verbose_name="Питомец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото питомца",
                "verbose_name_plural": "Фото питомцев",
            },
        ),
    ]
