# Generated by Django 5.2 on 2026-04-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0006_petphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="diet_additional_info",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Доп. Информация по питанию"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="diet_pattern",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Режим питания"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="diet_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Тип питания"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="specific_features",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Особенности"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="warning_tags",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Важные предупреждения"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Название породы"
            ),
        ),
    ]
