# Generated by Django 5.2 on 2026-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_pet_diet_additional_info_pet_diet_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='additional_info',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Дополнительная иформация'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], default='male', max_length=10, verbose_name='Пол'),
        ),
    ]
