from doby.settings import *

SECRET_KEY = Env.get_str('DJANGO_SECRET_KEY')
DEBUG = False
ALLOWED_HOSTS = Env.get_list('ALLOWED_HOSTS')
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True