# Generated by Django 5.2 on 2026-04-06 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatroom",
            options={"verbose_name": "Чат", "verbose_name_plural": "Чаты"},
        ),
    ]
