# Generated by Django 5.2 on 2026-04-19 15:20

import chats.storages
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_alter_chatroom_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=chats.storages.ProtectedStorage,
                upload_to=chats.storages.chat_media_upload_path,
                verbose_name="Прикрепленный файл",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("audio", "Аудиосообщение"),
                    ("video", "Видеосообщение"),
                    ("image", "Фотография"),
                    ("file", "Файл"),
                    ("text", "Текст"),
                ],
                default="text",
                max_length=100,
                verbose_name="Тип файла",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="original_filename",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Изначальное название файла",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(
                blank=True, max_length=4000, verbose_name="Сообщение"
            ),
        ),
    ]
