# Generated by Django 5.2 on 2026-04-02 18:44

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitterProfile",
            fields=[
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "experience_years",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество лет опыта",
                    ),
                ),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Стоимость в час",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Подтвержден"),
                ),
                (
                    "bio",
                    models.CharField(
                        blank=True, max_length=1500, verbose_name="Описание ситтера"
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль ситтера",
                "verbose_name_plural": "Профили ситтеров",
                "indexes": [
                    models.Index(
                        fields=["dt_updated"], name="sitter_profile_dt_updated_idx"
                    )
                ],
            },
        ),
    ]
