# Generated by Django 5.2 on 2026-03-11 20:12
import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitters", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitterprofile",
            options={
                "verbose_name": "Профиль ситтера",
                "verbose_name_plural": "Профили ситтеров",
            },
        ),
        migrations.AddField(
            model_name="sitterprofile",
            name="dt_created",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitterprofile",
            name="dt_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="sitterprofile",
            index=models.Index(
                fields=["dt_updated"], name="sitter_profile_dt_updated_idx"
            ),
        ),
    ]
