# Generated by Django 5.2 on 2026-03-11 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sitters",
            "0002_alter_sitterprofile_options_sitterprofile_dt_created_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sitterprofile",
            name="bio",
            field=models.CharField(
                blank=True, max_length=1500, verbose_name="Описание ситтера"
            ),
        ),
        migrations.AlterField(
            model_name="sitterprofile",
            name="experience_years",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество лет опыта",
            ),
        ),
    ]
