# Generated by Django 5.2 on 2026-06-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0002_sitterprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitterprofile',
            name='location_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitterprofile',
            name='location_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sitterprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.CreateModel(
            name='SitterService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('boarding', 'Передержка'), ('walking', 'Выгул'), ('grooming', 'Груминг'), ('training', 'Дрессировка')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitters.sitterprofile')),
            ],
            options={
                'verbose_name': 'Сервисы ситтера',
                'verbose_name_plural': 'Сервисы ситтеров',
            },
        ),
    ]
