# Generated by Django 5.2 on 2026-06-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitters", "0003_sitterprofile_address_sitterprofile_location_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitterservice",
            name="sitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="sitters.sitterprofile",
            ),
        ),
    ]
