# Generated by Django 5.2 on 2026-04-02 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
                ("dt_updated", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField(verbose_name="Начало")),
                ("end_datetime", models.DateTimeField(verbose_name="Конец")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждено"),
                            ("rejected", "Отклонено ситтером"),
                            ("cancelled_by_owner", "Отменено собачником"),
                            ("cancelled_by_sitter", "Отменено ситтером"),
                            ("completed", "Завершено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий к заказу"),
                ),
                (
                    "sitter_confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время подтверждения ситтером",
                    ),
                ),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pets.dog",
                        verbose_name="Собака",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Собачник",
                    ),
                ),
                (
                    "sitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitter_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ситтер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
                "indexes": [
                    models.Index(
                        fields=["owner", "status"],
                        name="bookings_bo_owner_i_0db98f_idx",
                    ),
                    models.Index(
                        fields=["sitter", "status"],
                        name="bookings_bo_sitter__94c41f_idx",
                    ),
                    models.Index(
                        fields=["start_datetime"], name="bookings_bo_start_d_d047d2_idx"
                    ),
                ],
            },
        ),
    ]
