# Generated by Django 5.2 on 2026-04-06 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="dog",
        ),
    ]
