# Generated by Django 5.2 on 2026-04-06 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_remove_booking_dog"),
        ("pets", "0002_pet_delete_dog"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pets.pet",
                verbose_name="Питомец",
            ),
        ),
    ]
