# Generated by Django 5.2 on 2026-04-24 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_pet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Собачник",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="sitter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sitter_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ситтер",
            ),
        ),
    ]
