# Generated by Django 5.2 on 2026-06-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_owner_alter_booking_sitter'),
        ('pets', '0008_pet_additional_info_pet_sex'),
        ('sitters', '0003_sitterprofile_address_sitterprofile_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_sitter__94c41f_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sitter',
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отмены собачником'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('boarding', 'Передержка'), ('walking', 'Выгул'), ('grooming', 'Груминг'), ('training', 'Дрессировка')], default='boarding', verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='booking',
            name='sitter_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitter_bookings', to='sitters.sitterprofile', verbose_name='Ситтер'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['sitter_new', 'status'], name='bookings_bo_sitter__99c1e8_idx'),
        ),
    ]
