# Generated by Django 5.2 on 2026-06-04 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_bookings_bo_sitter__94c41f_idx_and_more'),
        ('pets', '0008_pet_additional_info_pet_sex'),
        ('sitters', '0003_sitterprofile_address_sitterprofile_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_sitter__99c1e8_idx',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='sitter_new',
            new_name='sitter',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['sitter', 'status'], name='bookings_bo_sitter__94c41f_idx'),
        ),
    ]
